#!/usr/bin/env python3
"""
Master Portfolio Dashboard - Frank Fru
Displays all active cybersecurity projects in the portfolio.
"""

def show_dashboard():
    print("=================================================================")
    print("        CHIFRU19 CYBERSECURITY PORTFOLIO - MASTER DASHBOARD        ")
    print("=================================================================")
    print("[Project 1] scanner.py             - [VERIFIED & ACTIVE]")
    print("      Desc: Web App Vulnerability Scanner (Headers & Exposed Files)")
    print("-" * 65)
    print("[Project 2] log_analyzer.py        - [VERIFIED & ACTIVE]")
    print("      Desc: Log Analysis & Threat Detection (Brute-Force & Recon)")
    print("-" * 65)
    print("[Project 3] file_encryptor.py      - [VERIFIED & ACTIVE]")
    print("      Desc: Encrypted File Share & Secure Uploader (Fernet Encryption)")
    print("-" * 65)
    print("[Project 4] secret_scanner.py      - [VERIFIED & ACTIVE]")
    print("      Desc: Automated Git Repository Secret Scanner (Regex Leak Detector)")
    print("-" * 65)
    print("[Project 5] port_scanner.py        - [VERIFIED & ACTIVE]")
    print("      Desc: Network Port Scanner (Multi-threaded TCP Socket Mapper)")
    print("-" * 65)
    print("[Project 6] phishing_simulator.py  - [VERIFIED & ACTIVE]")
    print("      Desc: Phishing Awareness Simulation Tool (Educational Templates)")
    print("-" * 65)
    print("[Project 7] jwt_auditor.py         - [VERIFIED & ACTIVE]")
    print("      Desc: JWT Security Auditor (Misconfiguration & Signature Bypass Checker)")
    print("-" * 65)
    print("[Project 8] ssl_checker.py         - [VERIFIED & ACTIVE]")
    print("      Desc: SSL/TLS Certificate Expiration & Security Inspector")
    print("-" * 65)
    print("[Project 9] password_checker.py    - [VERIFIED & ACTIVE]")
    print("      Desc: Password Strength & Breach Checker (HIBP API Integration)")
    print("-" * 65)
    print("[Project 10] subdomain_scanner.py   - [VERIFIED & ACTIVE]")
    print("      Desc: Subdomain Enumerator (CRT.sh Public Record Multi-threaded Resolver)")
    print("-" * 65)
    print("[Project 11] s3_auditor.py          - [VERIFIED & ACTIVE]")
    print("      Desc: AWS S3 Storage Bucket Security & Exposure Auditor")
    print("-" * 65)
    print("[Project 12] threat_intel.py        - [VERIFIED & ACTIVE]")
    print("      Desc: Automated Threat Intelligence & IP Geolocation Lookup Tool")
    print("-" * 65)
    print("[Project 13] portfolio_dashboard.py - [VERIFIED & ACTIVE]")
    print("      Desc: Master Portfolio Command Center & Status Dashboard")
    print("=================================================================")
    print("[+] Portfolio Status: 13/13 Security Projects Active & Pushed to GitHub.")
    print("[+] Author: Frank Fru (chifru19@googlemail.com)")
    print("[+] Website: https://frankfru.com | GitHub: https://github.com/chifru19")
    print("=================================================================\n")

if __name__ == "__main__":
    show_dashboard()
